name: Run Cold-Email-Generator Backend

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v2 # Checkout the repository content to GitHub runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Install the Python version needed

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }} # Pass any secrets if needed
        run: python backend/main.py # Adjust the path to main.py relative to the repository root

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated logs" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main